### ISSUE TITLE
Angular Module ?

### ISSUE THREAD

**Issue by AndalusiaDev** [auth0/lock-passwordless#111]
Is there any Angular Module already developed for passwordless feature ? If not did you have any advice to integrate this code in Angular application ?

**Comment by christiannwamba** [comment]
Hi @AndalusiaDev 

We have plans on adding that in the next Angular SDK release. For now, I would suggest you write a service to help you do that. A quick tip is to make sure you handle the callbacks well using `$rootScope.$apply()` because the digest loop must have been completed before your callbacks are executed.

Thank you!

**Comment by AndalusiaDev** [comment]
Thank you @christiannwamba
