### ISSUE TITLE
Cut New Release

### ISSUE THREAD

**Issue by JackCA** [auth0/lock-passwordless#137]
I believe I'm running into the issues fixed in #109 but there is no longer a build directory/file in the repo and there hasn't been a release cut since then.

I have attempted to build myself, but it appears the zuul-ngrok fork you're using no longer exists...

Hoping for some insight from Auth0 team, thanks!

**Comment by luisrudge** [comment]
We're adding passwordless support to Lock itself (instead of keeping it as a separate project), but I'll try to cut a release with updated dependencies and pending PRs. If you want to subscribe to the lock repo, this is the PR: https://github.com/auth0/lock/pull/1070

You can safely remove the zuul-ngrok dependency if you want to build it yourself.

**Comment by JackCA** [comment]
@luisrudge cool, thanks. I will watch that thread, and if possible, a new version cut in the meantime would be appreciated. 👌
