### ISSUE TITLE
grant type /ro not allowed

### ISSUE THREAD

**Issue by ashish1dev** [auth0/lock-passwordless#138]
I keep getting this message : 

grant type 'http://auth0.com/oauth/legacy/grant-type/ro' not allowed.

I have following grant types enabled by default in client of Auth0.
1. Implicit,
2. Authorization Code,
3.  Refresh Token

I am building a nodejs app locally in MEAN stack.

Please help me resolve this issue.

Thanks,

**Comment by luisrudge** [comment]
This implementation of passwordless uses a few legacy endpoints that were disabled for new clients. You'll have to enable them in the dashboard to make it work. We're adding passwordless to lock itself (instead of keeping a separate project) and we'll make it work without using legacy endpoints. Please reach out to [support](https://support.auth0.com) to learn how to enable legacy grants in the dashboard
