### ISSUE TITLE
Is this project / feature still supported?

### ISSUE THREAD

**Issue by de-code** [auth0/lock-passwordless#141]
Thank you for providing Auth0 and the passwordless feature.

The last commit was a year ago (June 2016) and PRs have been ignored.

It's a good feature just seem to need a bit of TLC for production.

Is this still considered a supported feature for Auth0 or should we look elsewhere?

**Comment by luisrudge** [comment]
Hi! Thanks for the interest in our platform. We're in the process of merging the Passwordless feature into Lock, which is our main Widget. You can follow the progress [here](https://github.com/auth0/lock/pull/1070). Since this is not done yet, you can still use this project. For new clients, you'll have to add a few legacy grants in the dashboard because we're now disabling them by default, but everything still works. 🎉

**Comment by de-code** [comment]
Great, thank you. Might be worth adding in a note with that near the top of the project page.

**Comment by jeregrine** [comment]
@luisrudge Which legacy grants do you have to work for this work? I've enabled all grant types with the word "legacy" in the title and I still get:

```json
{"error":"invalid_request","error_description":"OIDC conformant clients cannot use /oauth/ro"}
```

That PR is almost 2 months old without any further action. Is there a timeline on this?

**Comment by luisrudge** [comment]
It's the Legacy:RO grant, but I don't think OIDC clients can use the `oauth/ro` endpoint at all. You'll have to disable OIDC to make it work.

The PR is done. We're waiting for docs and guidance on OIDC mode. This is happening soon-ish.

**Comment by jeregrine** [comment]
Thank you!! Didn't even realize that was an option.
