### ISSUE TITLE
unauthorized_client from Auth0 - Grant type not allowed

### ISSUE THREAD

**Issue by cdelgadob** [auth0/lock-passwordless#143]
When trying to validate the code with **`responseType: 'token'`**, Auth0 answers with this error:

`{"error":"unauthorized_client","description":"Grant type 'http://auth0.com/oauth/legacy/grant-type/ro' not allowed for the client."}`

How can I get around of this?

Carlos

**Comment by luisrudge** [comment]
Hi! We're working to join lock and lock-passwordless in the same project and this problem will go away. In the mean time, you'll have to enable this grant manually in your client. More info here: https://auth0.com/docs/clients/client-grant-types#information-for-existing-and-new-auth0-customers

I'm sorry you had to open an issue about this. I'll update the readme with this info. Thanks! 🎉

**Comment by luisrudge** [comment]
https://github.com/auth0/lock-passwordless/pull/144

**Comment by pmalek** [comment]
Hi there,

What's the status of this? Since I'm a new customer I cannot add any of the legacy grant types to my Clients anymore.
From what I understood is that I have to wait for this to be fixed/lock and lock-passwordless to be merged OR use the hosted pages, correct?

**Comment by luisrudge** [comment]
That's correct. I know it sucks to be stuck in that situation, but you can use the hosted login page for now until we're able to ship the updated Lock with support to passwordless.

**Comment by pmalek** [comment]
Can you specify how can I go about using passwordless with hosted pages?

Using an API would be quite simple as described here ( trigger email with code or link/sms via https://auth0.com/docs/api/authentication?http#get-code-or-link) or here https://auth0.com/docs/connections/passwordless using custom widgets ( I believe you should update these docs since lock-passwordless is not usable in this scenario right?).

All these docs don't mention how to use hosted pages with passwordless and I was not able to set it up via:
* disable user db connection
* enable one social login connection
* enable passwordless connection

after setting this up this way I get an Auth0 prompt on hosted page with solely one social login button.

What am I missing?

**Comment by luisrudge** [comment]
You will be able to do that in the new version. In the current version, however, you're limited to choosing social + one form of passwordless connections using `socialOrMagiclink`, `socialOrEmailcode` or `socialOrSms`.

**Comment by cdelgadob** [comment]
@luisrudge And when is the new version scheduled to be released? Any docs about the changes and features?
Thanks
Carlos

**Comment by luisrudge** [comment]
not yet @cdelgadob. we're working on the next major version of both lock and auth0-js that we need to release first. AFter that, we'll focus on getting this merged
