### ISSUE TITLE
React 0.14 support

### ISSUE THREAD

**Issue by joelburget** [auth0/lock-passwordless#63]
Currently `package.json` specifies `"react": "^0.13.3"`. This causes two versions of react to be bundled together if you're also using `0.14`. Perhaps we can change the upper bound?

**Comment by gnandretta** [comment]
I can upgrade the React dependency in a separate branch. That way you can specify something like `"auth0-lock-passwordless": "auth0/lock-passwordless#react-014rc"` in your _package.json_. Would that work for you?

Changing the upper bound won't be enough because React has been split in two packages and there were some API changes.

We plan to upgrade to _0.14_ as soon as it leaves the RC phase.

**Comment by joelburget** [comment]
Bleh. I was thinking you could just add `react-dom` as a dependency and convert all the uses of `render` and `findDOMNode` to `ReactDOM`, but apparently `react-dom` doesn't work with 0.13. I'll just fork so I can use this package in the meantime.

**Comment by gnandretta** [comment]
Cool! Please let me know if you encounter any issues during the upgrade.
